name: StimmungsSystem
version: 2.0.0
main: net.zerobuddys.stiummung.main.Main
api: ["1.0.8"]
author: ZeroBuddysYT
commands:
  pldev:
    description: Plugin Developer
    usage: /pldev
  happy:
    description: Happy Command
    usage: /happy
  angry:
    description: Angry Command
    usage: /angry
  alone:
    description: Alone Command
    usage: /alone
  amazed:
    description: Amazed Command
    usage: /amazed
  annoyed:
    description: Annoyed Command
    usage: /annoyed
  sad:
    description: Sad Command
    usage: /sad
  disappointed:
    description: Disappointed Command
    usage: /disappointed
  systeminfo:
    description: SystemInfo Command
    usage: /systeminfo
  corehelp:
    description: CoreHelp Command
    usage: /corehelp